name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-check:
    name: runner / tsc (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: error
          filter_mode: nofilter
          workdir: ./testdata
          tool_name: tsc-github-check
          fail_on_error: true
          tsc_flags: --project passing
      - id: action_failing_test
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          filter_mode: nofilter
          workdir: ./testdata
          tool_name: tsc-github-check
          fail_on_error: true
          tsc_flags: --project failing

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / tsc (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: error
          filter_mode: nofilter
          workdir: ./testdata
          tool_name: tsc-github-pr-check
          fail_on_error: true
          tsc_flags: --project passing
      - id: action_failing_test
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          filter_mode: nofilter
          workdir: ./testdata
          tool_name: tsc-github-pr-check
          fail_on_error: true
          tsc_flags: --project failing

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / tsc (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          filter_mode: nofilter
          workdir: ./testdata
          tool_name: tsc-github-pr-review
          fail_on_error: true
          tsc_flags: --project passing
      - id: action_failing_test
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          filter_mode: nofilter
          workdir: ./testdata
          tool_name: tsc-github-pr-review
          fail_on_error: true
          tsc_flags: --project failing
